import { vi, describe, it, expect, beforeEach, afterEach } from 'vitest'
import { vol } from 'memfs'
import { resolve } from 'node:path'

import { runTypesGenerator } from '../src/types-generator'
import { name as pkgName } from '../package.json'

// Mock fs/promises to use memfs
vi.mock('fs/promises', async () => {
  const memfs = await vi.importActual<typeof import('memfs')>('memfs')
  return memfs.fs.promises
})

// Mock glob so we control which files are discovered
vi.mock('glob', () => ({ glob: vi.fn() }))

describe('types-generator with merged namespaces (single file per language)', () => {
  beforeEach(async () => {
    vol.reset()
    vi.clearAllMocks()
    vi.spyOn(process, 'cwd').mockReturnValue('/project')

    const { glob } = await import('glob') as any
    // ensure the types.input glob resolves to our single merged file
    (glob as any).mockResolvedValue(['localization/translations/en.json'])

    // Create a merged translations file with the default namespace "translation"
    vol.fromJSON({
      '/project/localization/translations/en.json': JSON.stringify({
        translation: {
          addTerm: {
            tabTitle: 'Add clue'
          }
        }
      }, null, 2),
    })
  })

  afterEach(() => {
    vi.restoreAllMocks()
  })

  it('should treat merged-language-file contents as namespaces (use "translation" namespace) when generating types', async () => {
    const config: any = {
      locales: ['en'],
      extract: {
        mergeNamespaces: true,
        output: 'localization/translations/{{language}}.json',
      },
      types: {
        enableSelector: true,
        input: ['localization/translations/en.json'],
        output: 'localization/types/i18next.d.ts',
        resourcesFile: 'localization/types/resources.d.ts',
      },
    }

    await runTypesGenerator(config)

    const resourcesPath = resolve('/project', config.types.resourcesFile)
    const content = await vol.promises.readFile(resourcesPath, 'utf8')
    expect(content).toEqual(`// This file is automatically generated by ${pkgName}. Do not edit manually.
export default interface Resources {
  "translation": {
    "addTerm": {
      "tabTitle": "Add clue"
    }
  }
}
`)
  })
})
